"""Built-in templates and categories inserted on first start (editable afterwards)."""

from __future__ import annotations

W, H = 1080, 1350

_FOOTER = {"type": "text", "slot": "footer", "box": [60, 1270, 960, 50], "font_size": 28, "min_font_size": 20, "color": "#e2e8f0", "align": "left", "max_lines": 1}
_LOGO = {"type": "logo", "box": [900, 40, 140, 140]}

DEFAULT_TEMPLATES: list[dict] = [
    {
        "key": "announcement",
        "name": "Announcement",
        "description": "Bold headline on brand colour with a highlighted CTA.",
        "layout": {
            "background": {"type": "gradient", "from": "{primary}", "to": "#0f172a"},
            "elements": [
                {"type": "text", "text": "ANNOUNCEMENT", "box": [60, 80, 700, 60], "font_size": 34, "bold": True, "color": "{secondary}", "max_lines": 1},
                {"type": "text", "slot": "headline", "box": [60, 200, 960, 420], "font_size": 96, "min_font_size": 48, "bold": True, "color": "#ffffff", "max_lines": 4},
                {"type": "text", "slot": "subtitle", "box": [60, 640, 960, 200], "font_size": 44, "min_font_size": 28, "color": "#cbd5e1", "max_lines": 4},
                {"type": "image", "slot": "image", "box": [60, 860, 960, 280], "fit": "cover", "radius": 28, "opacity": 0.9},
                {
                    "type": "text",
                    "slot": "cta",
                    "box": [60, 1160, 960, 90],
                    "font_size": 38,
                    "min_font_size": 24,
                    "bold": True,
                    "color": "#0f172a",
                    "background": "{secondary}",
                    "padding": 18,
                    "max_lines": 1,
                },
                _FOOTER,
                _LOGO,
            ],
        },
    },
    {
        "key": "exam",
        "name": "Exam",
        "description": "Large image on top, exam headline and tip below.",
        "layout": {
            "background": {"type": "color", "color": "#0f172a"},
            "elements": [
                {"type": "image", "slot": "image", "box": [0, 0, W, 760], "fit": "cover"},
                {"type": "rect", "box": [0, 700, W, 650], "color": "#0f172a", "opacity": 1},
                {"type": "text", "slot": "category", "box": [60, 730, 600, 50], "font_size": 30, "bold": True, "color": "{secondary}", "uppercase": True, "max_lines": 1},
                {"type": "text", "slot": "headline", "box": [60, 790, 960, 260], "font_size": 80, "min_font_size": 40, "bold": True, "color": "#ffffff", "max_lines": 3},
                {"type": "text", "slot": "subtitle", "box": [60, 1060, 960, 120], "font_size": 38, "min_font_size": 26, "color": "#cbd5e1", "max_lines": 3},
                {"type": "text", "slot": "cta", "box": [60, 1180, 960, 80], "font_size": 34, "min_font_size": 22, "bold": True, "color": "{secondary}", "max_lines": 1},
                _FOOTER,
                _LOGO,
            ],
        },
    },
    {
        "key": "promotional",
        "name": "Promotional",
        "description": "Full-bleed image with dark overlay and strong CTA button.",
        "layout": {
            "background": {"type": "color", "color": "{primary}"},
            "elements": [
                {"type": "image", "slot": "image", "box": [0, 0, W, H], "fit": "cover", "placeholder_color": "{primary}"},
                {"type": "rect", "box": [0, 0, W, H], "color": "#000000", "opacity": 0.45},
                {
                    "type": "text",
                    "slot": "headline",
                    "box": [70, 560, 940, 360],
                    "font_size": 100,
                    "min_font_size": 48,
                    "bold": True,
                    "color": "#ffffff",
                    "align": "center",
                    "valign": "middle",
                    "max_lines": 4,
                },
                {"type": "text", "slot": "subtitle", "box": [90, 930, 900, 140], "font_size": 40, "min_font_size": 26, "color": "#f1f5f9", "align": "center", "max_lines": 3},
                {
                    "type": "text",
                    "slot": "cta",
                    "box": [140, 1100, 800, 110],
                    "font_size": 40,
                    "min_font_size": 24,
                    "bold": True,
                    "color": "#0f172a",
                    "background": "{secondary}",
                    "padding": 22,
                    "align": "center",
                    "max_lines": 1,
                },
                {**_FOOTER, "align": "center"},
                _LOGO,
            ],
        },
    },
    {
        "key": "educational",
        "name": "Educational",
        "description": "Light card layout for tips and explainers.",
        "layout": {
            "background": {"type": "color", "color": "#f8fafc"},
            "elements": [
                {"type": "rect", "box": [0, 0, W, 16], "color": "{primary}"},
                {"type": "text", "slot": "category", "box": [60, 60, 700, 50], "font_size": 30, "bold": True, "color": "{primary}", "uppercase": True, "max_lines": 1},
                {"type": "text", "slot": "headline", "box": [60, 130, 960, 300], "font_size": 76, "min_font_size": 40, "bold": True, "color": "#0f172a", "max_lines": 3},
                {"type": "image", "slot": "image", "box": [60, 450, 960, 560], "fit": "cover", "radius": 32},
                {"type": "text", "slot": "subtitle", "box": [60, 1040, 960, 130], "font_size": 38, "min_font_size": 24, "color": "#334155", "max_lines": 3},
                {"type": "text", "slot": "cta", "box": [60, 1180, 960, 70], "font_size": 32, "min_font_size": 22, "bold": True, "color": "{primary}", "max_lines": 1},
                {**_FOOTER, "color": "#64748b"},
                _LOGO,
            ],
        },
    },
    {
        "key": "batch",
        "name": "Batch",
        "description": "Batch/class focused layout with side image.",
        "layout": {
            "background": {"type": "gradient", "from": "#0f172a", "to": "{primary}"},
            "elements": [
                {"type": "image", "slot": "image", "box": [540, 0, 540, H], "fit": "cover", "opacity": 0.85},
                {"type": "rect", "box": [0, 0, 600, H], "color": "#0f172a", "opacity": 0.85},
                {"type": "text", "slot": "category", "box": [50, 80, 500, 50], "font_size": 30, "bold": True, "color": "{secondary}", "uppercase": True, "max_lines": 1},
                {"type": "text", "slot": "headline", "box": [50, 160, 500, 520], "font_size": 76, "min_font_size": 36, "bold": True, "color": "#ffffff", "max_lines": 6},
                {"type": "text", "slot": "subtitle", "box": [50, 700, 500, 300], "font_size": 38, "min_font_size": 24, "color": "#cbd5e1", "max_lines": 6},
                {
                    "type": "text",
                    "slot": "cta",
                    "box": [50, 1060, 500, 150],
                    "font_size": 34,
                    "min_font_size": 22,
                    "bold": True,
                    "color": "#0f172a",
                    "background": "{secondary}",
                    "padding": 18,
                    "max_lines": 2,
                },
                {**_FOOTER, "box": [50, 1270, 500, 50]},
            ],
        },
    },
    {
        "key": "quote",
        "name": "Quote",
        "description": "Centered quote/motivation text.",
        "layout": {
            "background": {"type": "gradient", "from": "{primary}", "to": "{secondary}"},
            "elements": [
                {"type": "text", "text": "“", "box": [60, 120, 200, 200], "font_size": 220, "bold": True, "color": "#ffffff", "max_lines": 1},
                {
                    "type": "text",
                    "slot": "headline",
                    "box": [100, 330, 880, 560],
                    "font_size": 84,
                    "min_font_size": 40,
                    "bold": True,
                    "color": "#ffffff",
                    "align": "center",
                    "valign": "middle",
                    "max_lines": 6,
                },
                {"type": "text", "slot": "subtitle", "box": [100, 920, 880, 160], "font_size": 40, "min_font_size": 26, "color": "#f8fafc", "align": "center", "max_lines": 3},
                {**_FOOTER, "align": "center"},
                _LOGO,
            ],
        },
    },
    {
        "key": "event",
        "name": "Event",
        "description": "Event layout: image band, headline, details and CTA.",
        "layout": {
            "background": {"type": "color", "color": "#111827"},
            "elements": [
                {"type": "image", "slot": "image", "box": [0, 0, W, 620], "fit": "cover"},
                {"type": "rect", "box": [0, 600, W, 12], "color": "{secondary}"},
                {"type": "text", "text": "EVENT", "box": [60, 650, 400, 50], "font_size": 32, "bold": True, "color": "{secondary}", "max_lines": 1},
                {"type": "text", "slot": "headline", "box": [60, 710, 960, 270], "font_size": 80, "min_font_size": 40, "bold": True, "color": "#ffffff", "max_lines": 3},
                {"type": "text", "slot": "subtitle", "box": [60, 990, 960, 160], "font_size": 38, "min_font_size": 24, "color": "#d1d5db", "max_lines": 4},
                {
                    "type": "text",
                    "slot": "cta",
                    "box": [60, 1160, 960, 90],
                    "font_size": 36,
                    "min_font_size": 22,
                    "bold": True,
                    "color": "#111827",
                    "background": "{secondary}",
                    "padding": 18,
                    "max_lines": 1,
                },
                _FOOTER,
                _LOGO,
            ],
        },
    },
]

DEFAULT_CATEGORIES: list[dict] = [
    {
        "key": "NORMAL",
        "name": "Normal",
        "description": "General company content.",
        "template": "educational",
        "color": "#6366f1",
        "ai_guidance": "Friendly, useful general content for followers.",
    },
    {
        "key": "BATCH",
        "name": "Batch",
        "description": "Content for a particular student/customer batch.",
        "template": "batch",
        "color": "#0ea5e9",
        "ai_guidance": "Speak directly to members of the named batch. Only mention batch timings/dates if provided.",
    },
    {
        "key": "CLASS_SPECIFIC",
        "name": "Class specific",
        "description": "Content for a specific class/course.",
        "template": "educational",
        "color": "#14b8a6",
        "ai_guidance": "Focus on the named class/course. Do not invent syllabus or course details.",
    },
    {
        "key": "EXAM",
        "name": "Exam",
        "description": "Exam preparation, announcements and reminders.",
        "template": "exam",
        "color": "#f97316",
        "ai_guidance": "Practical, motivating exam content. Never invent exam names, dates or patterns.",
    },
    {
        "key": "IMPORTANT",
        "name": "Important",
        "description": "Important company announcements.",
        "template": "announcement",
        "color": "#ef4444",
        "ai_guidance": "Clear, scannable announcement. State only the facts given in the input.",
    },
    {
        "key": "PROMOTIONAL",
        "name": "Promotional",
        "description": "Marketing/promotional content.",
        "template": "promotional",
        "color": "#eab308",
        "ai_guidance": "Persuasive but honest. Never invent prices, discounts, deadlines or results.",
    },
    {
        "key": "RANDOM",
        "name": "Random / Ideas",
        "description": "AI-generated content ideas.",
        "template": "quote",
        "color": "#a855f7",
        "ai_guidance": "Creative, engaging ideas that fit the brand.",
    },
]
