"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 14:01:17.460945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('brand_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('words_to_use', sa.JSON(), nullable=False),
    sa.Column('words_to_avoid', sa.JSON(), nullable=False),
    sa.Column('cta_style', sa.Text(), nullable=False),
    sa.Column('hashtag_strategy', sa.Text(), nullable=False),
    sa.Column('default_hashtags', sa.JSON(), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('content_restrictions', sa.Text(), nullable=False),
    sa.Column('default_language', sa.String(length=50), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=False),
    sa.Column('knowledge', sa.JSON(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instagram_handle', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=False),
    sa.Column('suggested_format', sa.String(length=100), nullable=False),
    sa.Column('target_audience', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('login_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_source', sa.String(length=20), nullable=False),
    sa.Column('token_expires_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('token_obtained_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('token_last_refreshed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_success_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('last_error_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_key'), 'templates', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('competitor_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('content_topic', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('caption_summary', sa.Text(), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('posting_frequency', sa.String(length=100), nullable=False),
    sa.Column('observed_strategy', sa.Text(), nullable=False),
    sa.Column('cta_used', sa.String(length=500), nullable=False),
    sa.Column('engagement_notes', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_observations_competitor_id'), 'competitor_observations', ['competitor_id'], unique=False)
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_guidance', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('default_template_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_categories_key'), 'content_categories', ['key'], unique=True)
    op.create_table('strategy_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('use_in_generation', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('post_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('generation_lead_hours', sa.Integer(), nullable=False),
    sa.Column('auto_generate', sa.Boolean(), nullable=False),
    sa.Column('auto_schedule_on_approval', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_rotation', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('topic_pool', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.String(length=500), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('target_audience', sa.String(length=500), nullable=False),
    sa.Column('tone', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('important_info', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('brand_instructions', sa.Text(), nullable=False),
    sa.Column('reference_material', sa.Text(), nullable=False),
    sa.Column('image_instructions', sa.Text(), nullable=False),
    sa.Column('desired_publish_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('alternative_caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('raw_image_url', sa.String(length=1024), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('review_flags', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('flags_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('instagram_container_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_media_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_permalink', sa.String(length=1024), nullable=False),
    sa.Column('published_via_mock', sa.Boolean(), nullable=False),
    sa.Column('publish_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('publishing_started_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('metrics_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('image_provider', sa.String(length=50), nullable=False),
    sa.Column('image_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('image_generation_ms', sa.Integer(), nullable=True),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('image_regeneration_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sheet_synced_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['recurring_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_media_id'),
    sa.UniqueConstraint('schedule_id', 'desired_publish_at', name='uq_post_schedule_slot')
    )
    op.create_index(op.f('ix_posts_channel'), 'posts', ['channel'], unique=False)
    op.create_index(op.f('ix_posts_schedule_id'), 'posts', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_created_at'), 'integration_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_logs_source'), 'integration_logs', ['source'], unique=False)
    op.create_table('post_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_events_post_id'), 'post_events', ['post_id'], unique=False)
    op.create_table('publish_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('started_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('transient', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('media_id', sa.String(length=100), nullable=True),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_attempts_post_id'), 'publish_attempts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publish_attempts_post_id'), table_name='publish_attempts')
    op.drop_table('publish_attempts')
    op.drop_index(op.f('ix_post_events_post_id'), table_name='post_events')
    op.drop_table('post_events')
    op.drop_index(op.f('ix_integration_logs_source'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_created_at'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_schedule_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('recurring_schedules')
    op.drop_table('strategy_insights')
    op.drop_index(op.f('ix_content_categories_key'), table_name='content_categories')
    op.drop_table('content_categories')
    op.drop_index(op.f('ix_competitor_observations_competitor_id'), table_name='competitor_observations')
    op.drop_table('competitor_observations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_key'), table_name='templates')
    op.drop_table('templates')
    op.drop_table('instagram_accounts')
    op.drop_table('content_ideas')
    op.drop_table('competitors')
    op.drop_table('brand_profile')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
